import tempfile
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from vehicle_sim.config import REPORT_FILENAME
from vehicle_sim.model import calculate_metrics


def render_latex_eq(latex_str, filename, fontsize=14):
    fig = plt.figure(figsize=(10, 1))
    fig.text(0.5, 0.5, f"${latex_str}$", size=fontsize, ha="center", va="center")
    plt.axis("off")
    plt.savefig(filename, dpi=200, bbox_inches="tight", pad_inches=0.1)
    plt.close(fig)


def create_dynamics_plot(data, output_path):
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(8, 10), sharex=True)

    ax1.plot(data["t"], np.array(data["v"]) * 2.237, linewidth=2, color="#1f77b4")
    ax1.set_ylabel("Speed (mph)", fontweight="bold")
    ax1.set_title("Longitudinal Velocity Profile", fontweight="bold")
    ax1.grid(True, alpha=0.3)

    ax2.plot(data["t"], data["rpm"], color="#d62728", linewidth=1.5)
    ax2.set_ylabel("Engine RPM", fontweight="bold")
    ax2.set_title("Engine Speed & Shift Points", fontweight="bold")
    ax2.grid(True, alpha=0.3)

    ax3.plot(data["t"], np.array(data["slip"]) * 100, color="#2ca02c", label="Longitudinal Slip")
    ax3.set_ylabel("Slip Ratio (%)", fontweight="bold")
    ax3.set_xlabel("Time (s)", fontweight="bold")
    ax3.set_title("Tire Traction Dynamics", fontweight="bold")
    ax3.axhline(y=15, color="gray", linestyle="--", alpha=0.5, label="Traction Limit")
    ax3.set_ylim(-5, 40)
    ax3.legend(loc="upper right")
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(output_path, dpi=200)
    plt.close(fig)


def append_equation_block(story, title, description, latex, image_path, width_cm, styles):
    story.append(Paragraph(title, styles["h3"]))
    story.append(Paragraph(description, styles["body"]))
    render_latex_eq(latex, image_path)
    story.append(Image(str(image_path), width=width_cm * cm, height=1.5 * cm))


def build_report_styles():
    base_styles = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "MainTitle",
            parent=base_styles["Title"],
            fontSize=24,
            spaceAfter=5,
            alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "SubTitle",
            parent=base_styles["Normal"],
            fontSize=12,
            spaceAfter=20,
            alignment=TA_CENTER,
        ),
        "h2": ParagraphStyle(
            "Heading2Custom",
            parent=base_styles["Heading2"],
            fontSize=14,
            spaceBefore=15,
            spaceAfter=10,
            textColor=colors.navy,
        ),
        "h3": ParagraphStyle(
            "Heading3Custom",
            parent=base_styles["Heading3"],
            fontSize=12,
            spaceBefore=10,
            spaceAfter=5,
        ),
        "body": ParagraphStyle(
            "JustifiedBody",
            parent=base_styles["BodyText"],
            alignment=TA_JUSTIFY,
            leading=14,
            fontSize=10,
        ),
    }


def generate_pdf_report(data, output_path: str | Path | None = None) -> Path:
    metrics = calculate_metrics(data)
    final_path = Path(output_path) if output_path else Path.cwd() / REPORT_FILENAME
    doc = SimpleDocTemplate(
        str(final_path),
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = build_report_styles()
    story = []

    story.append(Paragraph("High-Fidelity Vehicle Dynamics Analysis", styles["title"]))
    story.append(Paragraph("Generated by Engineering Simulation Core v3.0", styles["subtitle"]))
    story.append(Spacer(1, 10))

    table_data = [
        ["Metric", "Result", "Notes"],
        [
            "0 - 60 mph",
            f"{metrics.zero_to_sixty_s:.2f} s" if metrics.zero_to_sixty_s is not None else "N/A",
            "Includes shift times",
        ],
        ["Top Speed", f"{metrics.top_speed_mph:.1f} mph", "Drag limited"],
        ["Peak Long. G", f"{metrics.peak_longitudinal_g:.2f} G", "Launch grip"],
        ["Traction Limited", f"{metrics.traction_limited_pct:.1f} %", "% of run with wheelspin"],
    ]

    results_table = Table(table_data, colWidths=[5 * cm, 5 * cm, 6 * cm])
    results_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.navy),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 12),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),
                ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("GRID", (0, 0), (-1, -1), 1.5, colors.black),
                ("BOX", (0, 0), (-1, -1), 2, colors.black),
            ]
        )
    )
    story.append(results_table)
    story.append(Spacer(1, 20))

    zero_to_sixty_text = (
        f"{metrics.zero_to_sixty_s:.2f}s" if metrics.zero_to_sixty_s is not None else "the target speed window"
    )
    story.append(
        Paragraph(
            f"""
            <b>Engineering Justification:</b><br/>
            The simulation results reflect the coupling between engine inertia, tire tractive limits, and aerodynamic drag.
            The vehicle achieved a 0-60 time of <b>{zero_to_sixty_text}</b>.
            <br/><br/>
            1. <b>Launch Phase:</b> The tire slip plot indicates whether the vehicle is traction-limited or power-limited.
            The <i>Traction Limited</i> metric ({metrics.traction_limited_pct:.1f}%) quantifies how much of the run was spent modulating wheelspin.
            <br/>
            2. <b>Shift Dynamics:</b> The torque interruption visible in acceleration data corresponds to the clutch opening during gear shifts.
            <br/>
            3. <b>Aerodynamic Drag:</b> As velocity increases, the acceleration rate decays non-linearly ($F_d \\propto v^2$),
            eventually resulting in the drag-limited top speed.
            """,
            styles["body"],
        )
    )
    story.append(PageBreak())

    story.append(Paragraph("<b>Appendix A: Dynamics Visualization</b>", styles["h2"]))
    story.append(Spacer(1, 10))

    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        plot_path = temp_path / "plots.png"
        create_dynamics_plot(data, plot_path)
        story.append(Image(str(plot_path), width=16 * cm, height=20 * cm))
        story.append(PageBreak())

        story.append(Paragraph("<b>Appendix B: Mathematical Framework</b>", styles["h2"]))
        story.append(
            Paragraph(
                "The simulation uses a 3-degree-of-freedom explicit ODE solver to couple engine speed, wheel speed, and vehicle speed.",
                styles["body"],
            )
        )
        story.append(Spacer(1, 10))

        append_equation_block(
            story,
            "<b>1. Rotational Engine Dynamics</b>",
            "The engine is modeled as a rotating inertia subject to combustion torque, internal friction, and clutch loading.",
            r"I_{e} \frac{d\omega_e}{dt} = T_{comb}(\omega_e, \theta_{thr}) - T_{clutch} - T_{fric}",
            temp_path / "eq_eng.png",
            10,
            styles,
        )
        append_equation_block(
            story,
            "<b>2. Clutch & Transmission Kinematics</b>",
            "The clutch is modeled as a variable stiffness coupler. When slipping, torque transfer is proportional to clamp load and speed delta.",
            r"T_{clutch} = k_{gain} \cdot \mu_{clutch} \cdot (\omega_e - \omega_w \cdot G_{gear} \cdot G_{final})",
            temp_path / "eq_clutch.png",
            12,
            styles,
        )
        append_equation_block(
            story,
            "<b>3. Pacejka Tire Model (Magic Formula)</b>",
            "Longitudinal traction starts from the slip ratio definition below.",
            r"\kappa = \frac{\omega_w r_{tire} - v}{\max(|v|, \epsilon)}",
            temp_path / "eq_slip.png",
            6,
            styles,
        )
        story.append(
            Paragraph(
                "The resulting tractive force is then computed with a load-sensitive Magic Formula relationship.",
                styles["body"],
            )
        )
        render_latex_eq(
            r"F_x = D \sin(C \arctan(B\kappa - E(B\kappa - \arctan(B\kappa)))) \cdot \lambda_{\mu,z}",
            temp_path / "eq_pacejka.png",
        )
        story.append(Image(str(temp_path / "eq_pacejka.png"), width=13 * cm, height=1.5 * cm))
        append_equation_block(
            story,
            "<b>4. Quasi-Static Load Transfer</b>",
            "Vertical load on the drive tires varies dynamically with longitudinal acceleration.",
            r"F_{z,rear} = \frac{mg}{2} + \frac{h_{cg}}{L} m a_x",
            temp_path / "eq_load.png",
            8,
            styles,
        )
        append_equation_block(
            story,
            "<b>5. Vehicle Equations of Motion</b>",
            "Chassis acceleration is solved from tractive and resistive force balance.",
            r"m \frac{dv}{dt} = F_x - \frac{1}{2}\rho C_d A v^2 - C_{rr} m g",
            temp_path / "eq_newton.png",
            10,
            styles,
        )

        doc.build(story)

    return final_path
